### ISSUE TITLE
Diff not being displayed

### ISSUE THREAD

**Issue by hakanai** [usultis/junit-expected-diff-plugin#1]
The diff is not showing for any of our test failures. We have turned the feature on for all builds. (It's a bit sad that it isn't just enabled for all builds automatically.)

I don't know if you're assuming a particular regex, but our failures look like this. The specifics of the spacing are probably wrong because I had to reformat to get GitHub to recognise it as preformatted text.

```
Error Message

Expected: is "Row 0\n  ATXNewFromeDR: false\n  BinaryPath: ../00/00/00/00000000.eml\n  DocID: 00000000\n  EDDFileMD5: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n  EmbeddedFileCount: 1\n  GroupID: 00000000\n  ID: 1\n  ImagePath: ../00/00/00/00.tif\n  LastRasterErrorNumber: 0\n  ObjectsEmbeddedIntoEmailBodyCount: 0\n  Pages: 1\n"
     but: was "Row 0\n  ATXNewFromeDR: false\n  BinaryPath: ../00/00/00/00000000.eml\n  DocID: 00000000\n  EDDFileMD5: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n  EmbeddedFileCount: 1\n  GroupID: 00000000\n  ID: 1\n  ImagePath: ../00/00/00/00.tif\n  Pages: 1\n"

Stacktrace

junit.framework.AssertionFailedError: 
Expected: is "Row 0\n  ATXNewFromeDR: false\n  BinaryPath: ../00/00/00/00000000.eml\n  DocID: 00000000\n  EDDFileMD5: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n  EmbeddedFileCount: 1\n  GroupID: 00000000\n  ID: 1\n  ImagePath: ../00/00/00/00.tif\n  LastRasterErrorNumber: 0\n  ObjectsEmbeddedIntoEmailBodyCount: 0\n  Pages: 1\n"
     but: was "Row 0\n  ATXNewFromeDR: false\n  BinaryPath: ../00/00/00/00000000.eml\n  DocID: 00000000\n  EDDFileMD5: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n  EmbeddedFileCount: 1\n  GroupID: 00000000\n  ID: 1\n  ImagePath: ../00/00/00/00.tif\n  Pages: 1\n"
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at com.acme.util.mdb.AccessDatabaseAsserts.assertDatabaseContents(AccessDatabaseAsserts.java:158)
    at com.acme.util.mdb.AccessDatabaseAsserts.assertDatabaseContents(AccessDatabaseAsserts.java:70)
    at com.acme.integration.export.legal.TestDiscoveryRadarExport.testRunner(TestDiscoveryRadarExport.java:270)
    [omitting rest of stack trace]
```

**Comment by hakanai** [comment]
Have I reported this in the wrong place or has the developer died?
